// Code generated by mockery v2.53.4. DO NOT EDIT.

package encryption_mocks

import (
	encryption "cloud-storage/encryption"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// SymmetricEncryptionProvider is an autogenerated mock type for the SymmetricEncryptionProvider type
type SymmetricEncryptionProvider struct {
	mock.Mock
}

type SymmetricEncryptionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SymmetricEncryptionProvider) EXPECT() *SymmetricEncryptionProvider_Expecter {
	return &SymmetricEncryptionProvider_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function with given fields: r, key, rs
func (_m *SymmetricEncryptionProvider) Encrypt(r io.Reader, key []byte, rs encryption.RandomSource) ([]byte, []byte, error) {
	ret := _m.Called(r, key, rs)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(io.Reader, []byte, encryption.RandomSource) ([]byte, []byte, error)); ok {
		return rf(r, key, rs)
	}
	if rf, ok := ret.Get(0).(func(io.Reader, []byte, encryption.RandomSource) []byte); ok {
		r0 = rf(r, key, rs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader, []byte, encryption.RandomSource) []byte); ok {
		r1 = rf(r, key, rs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(io.Reader, []byte, encryption.RandomSource) error); ok {
		r2 = rf(r, key, rs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SymmetricEncryptionProvider_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type SymmetricEncryptionProvider_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - r io.Reader
//   - key []byte
//   - rs encryption.RandomSource
func (_e *SymmetricEncryptionProvider_Expecter) Encrypt(r interface{}, key interface{}, rs interface{}) *SymmetricEncryptionProvider_Encrypt_Call {
	return &SymmetricEncryptionProvider_Encrypt_Call{Call: _e.mock.On("Encrypt", r, key, rs)}
}

func (_c *SymmetricEncryptionProvider_Encrypt_Call) Run(run func(r io.Reader, key []byte, rs encryption.RandomSource)) *SymmetricEncryptionProvider_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].([]byte), args[2].(encryption.RandomSource))
	})
	return _c
}

func (_c *SymmetricEncryptionProvider_Encrypt_Call) Return(ciphertext []byte, nonce []byte, err error) *SymmetricEncryptionProvider_Encrypt_Call {
	_c.Call.Return(ciphertext, nonce, err)
	return _c
}

func (_c *SymmetricEncryptionProvider_Encrypt_Call) RunAndReturn(run func(io.Reader, []byte, encryption.RandomSource) ([]byte, []byte, error)) *SymmetricEncryptionProvider_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewSymmetricEncryptionProvider creates a new instance of SymmetricEncryptionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSymmetricEncryptionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SymmetricEncryptionProvider {
	mock := &SymmetricEncryptionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
